/**
 * orbisapi
 * Polls is a simple API allowing consumers to view polls and vote in them.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RefreshToken { 
    /**
     * A valid refresh token which has the same user id as the Authorization token.
     */
    refresh_token?: string;
}

