/**
 * orbisapi
 * Polls is a simple API allowing consumers to view polls and vote in them.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TopRequest { 
    /**
     * the current status of this item. 0 = unset; 1 = accepted; 2 = not accepted; 3 = pending
     */
    status?: number;
    /**
     * the number of the torso id
     */
    torso_id?: number;
    /**
     * the valency type category
     */
    valency_type?: number;
    /**
     * the clothing type of this item
     */
    clothing_type?: number;
    /**
     * the percentage of polyester of a top
     */
    polyester_percentage?: number;
    /**
     * the cotton percentage of a top
     */
    cotton_percentage?: number;
    /**
     * the leather percentage of a top
     */
    leather_percentage?: number;
    /**
     * the silk percentage of a top
     */
    silk_percentage?: number;
    /**
     * the relative amount of items needed
     */
    relative_amount?: number;
}

