/**
 * orbisapi
 * Polls is a simple API allowing consumers to view polls and vote in them.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The credentials a user has to pass to login to the API
 */
export interface UserCredentials { 
    /**
     * The name of the user. Can be a username or an email address
     */
    name?: string;
    /**
     * The plain password of the user.
     */
    password?: string;
}

